config/routes.rb
Rails.application.routes.draw do
  
  resources :skills
  root 'page#home'
  resources :character_references
  resources :employment_records
  resources :educations
  resources :profiles
  resources :jobs
  devise_for :users do
    get 'login' => 'devise/sessions#create'
  end

end

app/models/employment_record.rb
class EmploymentRecord < ActiveRecord::Base
	belongs_to :profile
	belongs_to :user
end

app/controllers/employment_records_controller.rb
class EmploymentRecordsController < ApplicationController
  before_action :set_employment_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /employment_records
  # GET /employment_records.json
  def index
    @employment_records = EmploymentRecord.all
  end

  # GET /employment_records/1
  # GET /employment_records/1.json
  def show
  end

  # GET /employment_records/new
  def new
    # @employment_record = EmploymentRecord.new
    @employment_record = current_user.employment_records.build
  end

  # GET /employment_records/1/edit
  def edit
  end

  # POST /employment_records
  # POST /employment_records.json
  def create
    # @employment_record = EmploymentRecord.new(employment_record_params)
    @employment_record = current_user.employment_records.build(employment_record_params)
    respond_to do |format|
      if @employment_record.save
        format.html { redirect_to @employment_record, notice: 'Employment record was successfully created.' }
        format.json { render :show, status: :created, location: @employment_record }
      else
        format.html { render :new }
        format.json { render json: @employment_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employment_records/1
  # PATCH/PUT /employment_records/1.json
  def update
    respond_to do |format|
      if @employment_record.update(employment_record_params)
        format.html { redirect_to @employment_record, notice: 'Employment record was successfully updated.' }
        format.json { render :show, status: :ok, location: @employment_record }
      else
        format.html { render :edit }
        format.json { render json: @employment_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employment_records/1
  # DELETE /employment_records/1.json
  def destroy
    @employment_record.destroy
    respond_to do |format|
      format.html { redirect_to employment_records_url, notice: 'Employment record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employment_record
      @employment_record = EmploymentRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employment_record_params
      params.require(:employment_record).permit(:company_name, :company_address, :company_position, :date_start, :date_end, :profile_id)
    end
end

app/helpers/employment_records_helper.rb
module EmploymentRecordsHelper
end

app/views/employment_records/_form.html.erb
<%= form_for(@employment_record) do |f| %>
  <% if @employment_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employment_record.errors.count, "error") %> prohibited this employment_record from being saved:</h2>

      <ul>
      <% @employment_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :company_address %><br>
    <%= f.text_field :company_address %>
  </div>
  <div class="field">
    <%= f.label :company_position %><br>
    <%= f.text_field :company_position %>
  </div>
  <div class="field">
    <%= f.label :date_start %><br>
    <%= f.text_field :date_start %>
  </div>
  <div class="field">
    <%= f.label :date_end %><br>
    <%= f.text_field :date_end %>
  </div>
  <%= f.hidden_field :profile_id, :value => current_user.profile.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employment_records/edit.html.erb
<h1>Editing Employment Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @employment_record %> |
<%= link_to 'Back', employment_records_path %>

app/views/employment_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employment Records</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Company address</th>
      <th>Company position</th>
      <th>Date start</th>
      <th>Date end</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employment_records.each do |employment_record| %>
      <tr>
        <td><%= employment_record.company_name %></td>
        <td><%= employment_record.company_address %></td>
        <td><%= employment_record.company_position %></td>
        <td><%= employment_record.date_start %></td>
        <td><%= employment_record.date_end %></td>
        <td><%= link_to 'Show', employment_record %></td>
        <td><%= link_to 'Edit', edit_employment_record_path(employment_record) %></td>
        <td><%= link_to 'Destroy', employment_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employment record', new_employment_record_path %>

app/views/employment_records/new.html.erb
<h1>New Employment Record</h1>

<%= render 'form' %>

<%= link_to 'Back', employment_records_path %>

app/views/employment_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @employment_record.company_name %>
</p>

<p>
  <strong>Company address:</strong>
  <%= @employment_record.company_address %>
</p>

<p>
  <strong>Company position:</strong>
  <%= @employment_record.company_position %>
</p>

<p>
  <strong>Date start:</strong>
  <%= @employment_record.date_start %>
</p>

<p>
  <strong>Date end:</strong>
  <%= @employment_record.date_end %>
</p>

<%= link_to 'Edit', edit_employment_record_path(@employment_record) %> |
<%= link_to 'Back', employment_records_path %>