config/routes.rb
Rails.application.routes.draw do
  
  resources :skills
  root 'page#home'
  resources :character_references
  resources :employment_records
  resources :educations
  resources :profiles
  resources :jobs
  devise_for :users do
    get 'login' => 'devise/sessions#create'
  end

end

app/models/education.rb
class Education < ActiveRecord::Base
	belongs_to :profile
	belongs_to :user
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    #@education = Education.new
    @education = current_user.educations.build
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations
  # POST /educations.json
  def create
    #@education = Education.new(education_params)
    @education = current_user.educations.build(education_params)
    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url, notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(:school_name, :degree_receive, :year_attended, :profile_id)
    end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<%= form_for(@education) do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% @education.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :school_name %><br>
    <%= f.text_field :school_name %>
  </div>
  <div class="field">
    <%= f.label :degree_receive %><br>
    <%= f.text_field :degree_receive %>
  </div>
  <div class="field">
    <%= f.label :year_attended %><br>
    <%= f.text_field :year_attended %>
  </div>
  <%= f.hidden_field :profile_id, :value => current_user.profile.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/educations/edit.html.erb
<h1>Editing Education</h1>

<%= render 'form' %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Educations</h1>

<table>
  <thead>
    <tr>
      <th>School name</th>
      <th>Degree receive</th>
      <th>Year attended</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @educations.each do |education| %>
      <tr>
        <td><%= education.school_name %></td>
        <td><%= education.degree_receive %></td>
        <td><%= education.year_attended %></td>
        <td><%= link_to 'Show', education %></td>
        <td><%= link_to 'Edit', edit_education_path(education) %></td>
        <td><%= link_to 'Destroy', education, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Education', new_education_path %>

app/views/educations/new.html.erb
<h1>New Education</h1>

<%= render 'form' %>

<%= link_to 'Back', educations_path %>

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School name:</strong>
  <%= @education.school_name %>
</p>

<p>
  <strong>Degree receive:</strong>
  <%= @education.degree_receive %>
</p>

<p>
  <strong>Year attended:</strong>
  <%= @education.year_attended %>
</p>

<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>