config/routes.rb
Rails.application.routes.draw do
  
  resources :skills
  root 'page#home'
  resources :character_references
  resources :employment_records
  resources :educations
  resources :profiles
  resources :jobs
  devise_for :users do
    get 'login' => 'devise/sessions#create'
  end

end

app/views/layouts/_header.html.erb
<!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "HanepBuhay", root_path, class: "navbar-brand" %>
            </div>
             
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
            <% if user_signed_in? %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>
                        <% if current_user.profile.first_name == nil && current_user.profile.last_name == nil %>
                            <%= current_user.email %>
                        <% else %>
                            <%= current_user.profile.first_name %> <%= current_user.profile.last_name %>
                      <% end %> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/profiles/<%= current_user.profile.id %>/edit"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                        <%= link_to destroy_user_session_path, method: :delete do %>
                          <i class="fa fa-fw fa-power-off"></i> Log Out
                        <% end %>
                        </li>
                    </ul>
                </li>
                <% else %>
                    <li><%= link_to "Sign up", new_user_registration_path %></li>
                    <li><%= link_to "Login", new_user_session_path %></li>
                <% end %>
            </ul>
            
            <% if user_signed_in? %>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
            
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href="/profiles/<%= current_user.profile.id %>"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li>
                    
                    <li>
                        <%= link_to educations_path do %>
                        <i class="fa fa-fw fa-bar-chart-o"></i> Education
                        <% end %>
                    </li>
                     
                    <li>
                        <%= link_to skills_path do %>
                        <i class="fa fa-fw fa-table"></i> Skills
                        <% end %>
                    </li>
                    <li>
                        <%= link_to employment_records_path do %>
                        <i class="fa fa-fw fa-edit"></i> Employment Record
                        <% end %>
                    </li>
                    <li>
                        <%= link_to character_references_path do %>
                        <i class="fa fa-fw fa-edit"></i> Character References
                        <% end %>
                    </li>
                    
                </ul>
                
            </div>
            <!-- /.navbar-collapse -->
            <% end %>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hanepbuhay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    <div id="wrapper">
  <% else %>
    <div id="wrapper" style="padding-left:0;">
  <% end %>
    <!-- /#wrapper -->
    <%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>
<div>
	<!-- /#wrapper -->
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>